
services:
  filesharing:
    build: .
    container_name: fastapi-app
    ports:
      - "80:8000"
    restart: unless-stopped
    volumes:
      - ~/.aws/credentials:/root/.aws/credentials:ro
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminStrong
    volumes:
      - minio_data:/data
    restart: unless-stopped

  localstack:
    image: localstack/localstack:4.14
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sns,sqs,lambda
      - AWS_DEFAULT_REGION=eu-central-1
      - LAMBDA_EXECUTOR=docker

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: filesharing
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  minio_data:
